name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Raspberry Pi build
      run: CC=arm-linux-gnueabi-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=6 go build -ldflags="-extldflags=-static" -tags sqlite_omit_load_extension -o gatekeeper cmd/server.go

    - name: Save Pi Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: gatekeeper
        path: ./gatekeeper
